# Generated by Django 5.2.1 on 2025-05-16 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_count', models.IntegerField(default=0)),
                ('person_count', models.IntegerField(default=0)),
                ('congestion_level', models.CharField(choices=[('calm', 'Sakin'), ('normal', 'Normal'), ('busy', 'Yoğun'), ('very_busy', 'Çok Yoğun')], default='normal', max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_data', to='trafficapp.location')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
