# Generated by Django 5.0.1 on 2025-05-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficdata',
            name='congestion_level',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafficapp.location'),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
